final List<Map<String, dynamic>> hotelData = [
  {
    'name': 'The Plaza Hotel',
    'pricePerNight': 450,
    'city': 'New York',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Marriott Marquis',
    'pricePerNight': 300,
    'city': 'New York',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Hilton Midtown',
    'pricePerNight': 350,
    'city': 'New York',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Four Seasons New York',
    'pricePerNight': 600,
    'city': 'New York',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'The Standard High Line',
    'pricePerNight': 400,
    'city': 'New York',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Mandarin Oriental',
    'pricePerNight': 550,
    'city': 'New York',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'The Langham',
    'pricePerNight': 480,
    'city': 'New York',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'The Ritz London',
    'pricePerNight': 500,
    'city': 'London',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'The Savoy',
    'pricePerNight': 400,
    'city': 'London',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Claridge’s',
    'pricePerNight': 600,
    'city': 'London',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'The Dorchester',
    'pricePerNight': 550,
    'city': 'London',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Hotel Cafe Royal',
    'pricePerNight': 450,
    'city': 'London',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Brown’s Hotel',
    'pricePerNight': 500,
    'city': 'London',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Hôtel Ritz Paris',
    'pricePerNight': 700,
    'city': 'Paris',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Le Meurice',
    'pricePerNight': 550,
    'city': 'Paris',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Hôtel de Crillon',
    'pricePerNight': 650,
    'city': 'Paris',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Shangri-La Paris',
    'pricePerNight': 600,
    'city': 'Paris',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Le Bristol Paris',
    'pricePerNight': 500,
    'city': 'Paris',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Hotel Lutetia',
    'pricePerNight': 550,
    'city': 'Paris',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Park Hyatt Tokyo',
    'pricePerNight': 450,
    'city': 'Tokyo',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'The Peninsula Tokyo',
    'pricePerNight': 500,
    'city': 'Tokyo',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Hotel Okura Tokyo',
    'pricePerNight': 400,
    'city': 'Tokyo',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Conrad Tokyo',
    'pricePerNight': 550,
    'city': 'Tokyo',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Aman Tokyo',
    'pricePerNight': 800,
    'city': 'Tokyo',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Cerulean Tower Tokyu Hotel',
    'pricePerNight': 450,
    'city': 'Tokyo',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Shangri-La Sydney',
    'pricePerNight': 350,
    'city': 'Sydney',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Park Hyatt Sydney',
    'pricePerNight': 600,
    'city': 'Sydney',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Four Seasons Sydney',
    'pricePerNight': 400,
    'city': 'Sydney',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'InterContinental Sydney',
    'pricePerNight': 450,
    'city': 'Sydney',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'The Star Grand Hotel',
    'pricePerNight': 500,
    'city': 'Sydney',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Sofitel Sydney Darling Harbour',
    'pricePerNight': 550,
    'city': 'Sydney',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Hotel Stone Bridge',
    'pricePerNight': 120,
    'city': 'Skopje',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'DoubleTree by Hilton Skopje',
    'pricePerNight': 150,
    'city': 'Skopje',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Hotel Alexandar Square',
    'pricePerNight': 100,
    'city': 'Skopje',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Park Hotel & Spa',
    'pricePerNight': 200,
    'city': 'Skopje',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Limak Skopje Luxury Hotel',
    'pricePerNight': 180,
    'city': 'Skopje',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Bushi Resort & Spa',
    'pricePerNight': 170,
    'city': 'Skopje',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Hotel De L’Europe',
    'pricePerNight': 500,
    'city': 'Amsterdam',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'W Amsterdam',
    'pricePerNight': 450,
    'city': 'Amsterdam',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Andaz Amsterdam Prinsengracht',
    'pricePerNight': 550,
    'city': 'Amsterdam',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Pulitzer Amsterdam',
    'pricePerNight': 400,
    'city': 'Amsterdam',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'Kimpton De Witt Amsterdam',
    'pricePerNight': 350,
    'city': 'Amsterdam',
    "image": "lib/assets/images/hotel_image.png",
  },
  {
    'name': 'NH Collection Amsterdam Grand',
    'pricePerNight': 450,
    'city': 'Amsterdam',
    "image": "lib/assets/images/hotel_image.png",
  },
];
